context:
  version: "1.8"

package:
  name: cflow
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/cflow/cflow-${{ version }}.tar.bz2
  sha256: 8321627b55b6c7877f6a43fcc6f9f846a94b1476a081a035465f7a78d3499ab8

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - gettext-tools
    - make
  host:
    - libtool
    - if: not linux
      then: libintl-devel

tests:
  - script:
      - cflow --help

about:
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Generate call graphs from C code
  homepage: https://www.gnu.org/software/cflow/

extra:
  recipe-maintainers:
    - danielnachun
